"""add approval flags

Revision ID: b19e668b92b0
Revises: 008586bf649d
Create Date: 2026-01-20 17:18:51.072405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19e668b92b0'
down_revision = '008586bf649d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chemist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('approved')

    with op.batch_alter_table('chemist', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
